<?php

namespace Database\Seeders;

use App\Models\CentreStock;
use App\Models\Centre_stock;
use Illuminate\Database\Seeder;

class CentreStockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $CentreStock =[
            [
                'org_id'=>1,
                'stock_id'=>1,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>2,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>3,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>4,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>5,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>6,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>7,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>8,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>9,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>10,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>11,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>12,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>13,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>14,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>15,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>16,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>17,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>18,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>19,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>20,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>21,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>22,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>23,
                'quantity'=>202,
            ],
            [
                'org_id'=>1,
                'stock_id'=>24,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>25,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>26,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>27,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>28,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>29,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>30,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>31,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>32,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>33,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>34,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>35,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>36,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>37,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>38,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>39,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>40,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>41,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>42,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>43,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>44,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>45,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>46,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>47,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>48,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>49,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>50,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>51,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>52,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>53,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>54,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>55,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>56,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>57,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>58,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>59,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>60,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>61,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>62,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>63,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>64,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>65,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>66,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>67,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>68,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>69,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>70,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>71,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>72,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>73,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>74,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>75,
                'quantity'=>20,
            ],
            [
                'org_id'=>1,
                'stock_id'=>76,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>77,
                'quantity'=>27,
            ],
            //2

            [
                'org_id'=>2,
                'stock_id'=>1,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>2,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>3,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>4,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>5,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>6,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>7,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>8,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>9,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>10,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>11,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>12,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>13,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>14,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>15,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>16,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>17,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>18,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>19,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>20,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>21,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>22,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>23,
                'quantity'=>202,
            ],
            [
                'org_id'=>2,
                'stock_id'=>24,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>25,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>26,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>27,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>28,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>29,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>30,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>31,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>32,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>33,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>34,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>35,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>36,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>37,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>38,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>39,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>40,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>41,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>42,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>43,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>44,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>45,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>46,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>47,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>48,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>49,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>50,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>51,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>52,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>53,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>54,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>55,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>56,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>57,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>58,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>59,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>60,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>61,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>62,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>63,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>64,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>65,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>66,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>67,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>68,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>69,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>70,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>71,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>72,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>73,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>74,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>75,
                'quantity'=>20,
            ],
            [
                'org_id'=>2,
                'stock_id'=>76,
                'quantity'=>27,
            ],
            [
                'org_id'=>2,
                'stock_id'=>77,
                'quantity'=>27,
            ],
            //3

            [
                'org_id'=>3,
                'stock_id'=>1,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>2,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>3,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>4,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>5,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>6,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>7,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>8,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>9,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>10,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>11,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>12,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>13,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>14,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>15,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>16,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>17,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>18,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>19,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>20,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>21,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>22,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>23,
                'quantity'=>202,
            ],
            [
                'org_id'=>3,
                'stock_id'=>24,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>25,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>26,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>27,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>28,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>29,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>30,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>31,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>32,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>33,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>34,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>35,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>36,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>37,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>38,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>39,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>40,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>41,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>42,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>43,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>44,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>45,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>46,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>47,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>48,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>49,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>50,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>51,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>52,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>53,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>54,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>55,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>56,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>57,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>58,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>59,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>60,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>61,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>62,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>63,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>64,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>65,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>66,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>67,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>68,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>69,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>70,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>71,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>72,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>73,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>74,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>75,
                'quantity'=>20,
            ],
            [
                'org_id'=>3,
                'stock_id'=>76,
                'quantity'=>27,
            ],
            [
                'org_id'=>3,
                'stock_id'=>77,
                'quantity'=>27,
            ],
            //4
            [
                'org_id'=>4,
                'stock_id'=>1,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>2,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>3,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>4,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>5,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>6,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>7,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>8,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>9,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>10,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>11,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>12,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>13,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>14,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>15,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>16,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>17,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>18,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>19,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>20,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>21,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>22,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>23,
                'quantity'=>202,
            ],
            [
                'org_id'=>4,
                'stock_id'=>24,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>25,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>26,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>27,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>28,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>29,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>30,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>31,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>32,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>33,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>34,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>35,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>36,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>37,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>38,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>39,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>40,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>41,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>42,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>43,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>44,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>45,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>46,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>47,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>48,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>49,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>50,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>51,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>52,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>53,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>54,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>55,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>56,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>57,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>58,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>59,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>60,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>61,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>62,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>63,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>64,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>65,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>66,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>67,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>68,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>69,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>70,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>71,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>72,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>73,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>74,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>75,
                'quantity'=>20,
            ],
            [
                'org_id'=>4,
                'stock_id'=>76,
                'quantity'=>27,
            ],
            [
                'org_id'=>4,
                'stock_id'=>77,
                'quantity'=>27,
            ],
            //5
            [
                'org_id'=>5,
                'stock_id'=>1,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>2,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>3,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>4,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>5,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>6,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>7,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>8,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>9,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>10,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>11,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>12,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>13,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>14,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>15,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>16,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>17,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>18,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>19,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>20,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>21,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>22,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>23,
                'quantity'=>202,
            ],
            [
                'org_id'=>5,
                'stock_id'=>24,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>25,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>26,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>27,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>28,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>29,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>30,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>31,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>32,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>33,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>34,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>35,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>36,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>37,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>38,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>39,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>40,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>41,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>42,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>43,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>44,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>45,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>46,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>47,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>48,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>49,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>50,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>51,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>52,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>53,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>54,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>55,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>56,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>57,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>58,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>59,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>60,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>61,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>62,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>63,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>64,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>65,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>66,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>67,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>68,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>69,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>70,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>71,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>72,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>73,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>74,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>75,
                'quantity'=>20,
            ],
            [
                'org_id'=>5,
                'stock_id'=>76,
                'quantity'=>27,
            ],
            [
                'org_id'=>5,
                'stock_id'=>77,
                'quantity'=>27,
            ],
            //6
            [
                'org_id'=>6,
                'stock_id'=>1,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>2,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>3,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>4,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>5,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>6,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>7,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>8,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>9,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>10,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>11,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>12,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>13,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>14,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>15,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>16,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>17,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>18,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>19,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>20,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>21,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>22,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>23,
                'quantity'=>202,
            ],
            [
                'org_id'=>6,
                'stock_id'=>24,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>25,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>26,
                'quantity'=>27,
            ],
            [
                'org_id'=>1,
                'stock_id'=>27,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>28,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>29,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>30,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>31,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>32,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>33,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>34,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>35,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>36,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>37,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>38,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>39,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>40,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>41,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>42,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>43,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>44,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>45,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>46,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>47,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>48,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>49,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>50,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>51,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>52,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>53,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>54,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>55,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>56,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>57,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>58,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>59,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>60,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>61,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>62,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>63,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>64,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>65,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>66,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>67,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>68,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>69,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>70,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>71,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>72,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>73,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>74,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>75,
                'quantity'=>20,
            ],
            [
                'org_id'=>6,
                'stock_id'=>76,
                'quantity'=>27,
            ],
            [
                'org_id'=>6,
                'stock_id'=>77,
                'quantity'=>27,
            ],
           
        ];
        foreach ($CentreStock as $product){
            CentreStock::create($product);
        }
    }
}
